# Generated by Django 4.2.6 on 2023-11-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unimap', '0007_location_vote1_location_vote2_location_vote3_and_more'),
        ('users', '0002_customuser_is_admin_alter_customuser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorites',
            field=models.ManyToManyField(blank=True, to='unimap.location'),
        ),
    ]
