# Generated by Django 4.2.6 on 2023-10-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unimap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abbreviation', models.CharField(max_length=3)),
                ('zone_id', models.CharField(max_length=5)),
                ('description', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
