# Generated by Django 4.2.6 on 2023-11-07 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unimap', '0006_remove_vote_comment_remove_vote_upvote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='vote1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='vote2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='vote3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='vote4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='vote5',
            field=models.IntegerField(default=0),
        ),
    ]
