# Generated by Django 4.2.4 on 2023-10-14 20:19

from django.db import migrations, models
import django_google_maps.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Rental",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", django_google_maps.fields.AddressField(max_length=200)),
                (
                    "geolocation",
                    django_google_maps.fields.GeoLocationField(max_length=100),
                ),
            ],
        ),
    ]
