# Generated by Django 4.2.6 on 2023-10-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unimap', '0003_location_vote_delete_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='geolocation',
        ),
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
