# Generated by Django 4.2.6 on 2023-10-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unimap', '0004_remove_location_geolocation_location_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
