# Generated by Django 4.2.6 on 2023-10-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="status",
            field=models.CharField(
                choices=[("user", "User"), ("admin", "Admin")],
                default="regular",
                max_length=100,
            ),
        ),
    ]
